### ISSUE TITLE
bisdn linux 5.1: package python3-appdirs missing in repository

### ISSUE THREAD

**Issue by gmuehl4241** [bisdn/bisdn-linux#100]
The package python3-appdirs is missing in the bisdn linux 5.1 repository although some other python packages depend on it.  The consequence is that the latter cannot be installed.

 *   - nothing provides python3-appdirs needed by python3-twisted-core-22.2.0-r0.cortexa9-vfp

Best regards,

GM

**Comment by KanjiMonster** [comment]
Mh. I can confirm the package missing, but I wonder why. I will need to investigate.

**Comment by KanjiMonster** [comment]
I suspect this might be a bad interaction of s3 expiry rules and s3 sync that caused packages to be expired before they were copied to a permanent location. I will try to reproduce the missing packages.

**Comment by KanjiMonster** [comment]
While that can certainly happen, the culprit seems to be bitbake not triggering packaging some transitive dependencies. Will need to investigate more, while preparing to manually fixup the repos.

**Comment by KanjiMonster** [comment]
I manually added the missing python3 packages, and installing python3-twisted-core now works at least for me (and consequently openvswitch, where this came from).

Why bitbake is missing the appropriate RDEPENDS is currently under investigation.

**Comment by KanjiMonster** [comment]
Upstream patch for the issue: https://patchwork.yoctoproject.org/project/bitbake/patch/20240111172806.3311690-1-richard.purdie@linuxfoundation.org/
