### ISSUE TITLE
Edgecore AS4610-30T - Switch ports not showing with BISDN 5.x

### ISSUE THREAD

**Issue by eichholz** [bisdn/bisdn-linux#124]
Hi everyone,

I have an Edgecore AS4610-30T switch on which I installed BISDN Linux 5.2.0. However, I only see 18 ports, which don't even map to the first 18 physical ports of the switch. 
![Bildschirmfoto 2024-08-28 um 11 14 40](https://github.com/user-attachments/assets/7ae4a389-9077-4f49-b88d-b87ba8e669d7)

I also tried version 5.0.0 and there I can observe the same. With BISDN 4.8.3, however, things seem to work as expected.

![Bildschirmfoto 2024-08-28 um 11 18 23](https://github.com/user-attachments/assets/066118db-cc13-439f-a37d-d53bdd2aa638)

Do you have any hints on how to debug the issue? Is it a known issue/limitation?

**Comment by KanjiMonster** [comment]
I found a typo likely affecting port15 (ge14), please try if [this version](https://raw.githubusercontent.com/bisdn/meta-ofdpa/6bcd321cba75f739b9302508b2f201789caea110/recipes-ofdpa/ofdpa/ofdpa-platform/platform/arm-accton-as4610-30-r0/config.bcm) works better.

**Comment by eichholz** [comment]
Now it seems to work! Thank you very much. 

Out of curiosity, what is the reason that for some ports the dport mapping is identical to the switch's internal port and for some they seem to be pairwise switched?

**Comment by KanjiMonster** [comment]
I wasn't involved in the design process, but I would assume this is to ensure traces have similar lengths and avoid interference the internal ports get shuffled around.
