### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by CHmSID** [bisdn/bisdn-linux#125]
We found a steady memory leak while repeatedly calling the command `client_drivshell ps`.

![Screenshot_20240902_105653](https://github.com/user-attachments/assets/db743280-5ec6-4dba-8326-0cff07158b3b)

Hardware: Agema ag7648
OS: issue found on both BISDN 4.7.0 and 5.2.0

Steps to reproduce:
1. On a freshly installed BISDN OS (4.7.0 or 5.2.0, doesn't matter)
2. Run `sudo watch -n1 "client_drivshell ps"` in a `screen` for a longer period of time 
3. With graphs the issue is already visible within few hours, you can also probably save output of `free -m` every hour and compare

Notes:
- We found that the file `/tmp/ofdpa_client.log` is constantly growing (and thus might be contributing to the memory usage) I will attach this file here for investigation (truncated to fit within github upload limits)
- In this file we can also see that each call to `client_drivshell ps` opens a new datagram socket, but those socket files are not removed after the command is finished. Indeed `ls -l /tmp/ | grep fpc. | wc -l` returns a big number 167391 on our SDN after a few days of running. I'm not sure if this is related to the memory leak though.
- I also checked if memory is lost with other commands such as `onlpdump -S`, but it seems that at least this command is not leaking memory

[ofdpa_client.log](https://github.com/user-attachments/files/16835197/ofdpa_client.log)

I hope this is helpful. Let me know if you have any other questions.

Our use case is to find ports' status (up or down) so that we can report it in our metrics. We do not run `baseboxd` and so the ports are not visible to the kernel. Do you know of any alternatives that can be used to get this information?

**Comment by KanjiMonster** [comment]
Hi, thank you for the report! I have an idea about where this comes from, at least the growing log and the set of left over datagram sockets, though fixing this won't be super simple.

The information about port status is exposed via OpenFlow via the Port Table, and on userspace via `client_porttable_dump`:

```
client_port_table_dump
0x00000001 (type: physical (0x0), index = 1) | port1:
	config = 0x00000001, state = 0x00000001, mac = f88e.a127.ef97, max. speed = 1000000 kbps, current speed = 1000000 kbps
	CurrFeature: 0x2810, AdvertFeature: 0x402f, SupportedFeature: 0xe82f, PeerFeature: 0x0
...
0x00000035 (type: physical (0x0), index = 53) | port53:
	config = 0x00000000, state = 0x00000000, mac = f88e.a127.efcb, max. speed = 100000000 kbps, current speed = 100000000 kbps
	CurrFeature: 0x900, AdvertFeature: 0x0, SupportedFeature: 0xfc80, PeerFeature: 0x0
```

where the lowest bit in config means "port set down", and the bit in state means "no link" (so all zero means it does have a link). These are eqivalent to the OpenFlow config and state fields of ports.

But `client_port_table_dump` uses the same interface for accessing OF-DPA as `client_drivshell` does, so it will also cause the same log and socket spam. This affects all other client_* utilities, as well as the python bindings.

So the only way of obtaining that info without triggering the issue currently will be via OpenFlow from ofagent.

**Comment by KanjiMonster** [comment]
As a simple workaround against the log file growing, you can mark it as read only

```
chattr +i /tmp/ofdpa_client.log
```

The side effect of that is that it will start logging to stderr instead of stdout:

```
client_port_table_dump  1
<0> 2024-09-02 10:48:35 [03881]: Entering rpccltCommSetup: inst=1 msgseq=0x66d59803
<1> 2024-09-02 10:48:35 [03881]: Created datagram socket: inst=1 sockid=3881 sockfd=3 cliaddr=/tmp/fpc.03881
<0> 2024-09-02 10:48:35 [03881]: Leaving rpccltCommSetup: inst=1
<1> 2024-09-02 10:48:35 [03881]: rpccltSuppWrapperOfdpa (inst=1 grp=2): Initialized RPC client OFDPA function table.
0x00000001 (type: physical (0x0), index = 1) | port1:
	config = 0x00000001, state = 0x00000001, mac = f88e.a127.ef97, max. speed = 1000000 kbps, current speed = 1000000 kbps
	CurrFeature: 0x2810, AdvertFeature: 0x402f, SupportedFeature: 0xe82f, PeerFeature: 0x0
```

But as it is `stderr` and the normal output is `stdout`, you can at least filter it out.

**Comment by KanjiMonster** [comment]
> By python bindings do you mean the OFDPA bindings for python?

Yes, though I think there isn't much logged by default apart from startup, so if you controller has a persistent connection, then the log file doesn't grow apart from the first few lines.

AFAICT the issue is that on every new connection to OF-DPA, a few lines are written to the log, which eventually accumulates. And since the logfile is in /tmp, and /tmp is a ramdisk, it slowly eats up memory.

**Comment by KanjiMonster** [comment]
Both issues are fixed internally, and upcoming nightlies will include the fixes.
