### ISSUE TITLE
AS4610-30P Boot Loop Bug

### ISSUE THREAD

**Issue by abbahmed** [bisdn/bisdn-linux#134]
### Issue:
I have three EdgeCore AS4610-30P, which I have updated to the latest Onie Version AS4610-30-r0_ONIE_v2016_05_00_04.updater (https://support.edge-core.com/hc/article_attachments/360044855034) and also installed BISDN version 5.2.1 (http://repo.bisdn.de/pub/onie/generic-armel-iproc/onie-bisdn-generic-armel-iproc-v5.2.1.bin) however, the switch keeps boot looping, it works for a couple minutes but then stops. The ports have been set to: - to remove existing configuration and initialising the switch to forward traffic between all ports. I don't know why it keeps restarting, also I have changed the power supplies around and it doesn't seem to do anything.

BISDN_DEFAULT_CONFIG="simple-l2-bridge"

### Findings from EdgeCore:

> jesse_wang 王亮懿 (Tech Support System)
> Oct 22, 2024, 19:06 GMT+8
> .....
> I tested to install the image as in your link to a AS4610-30P in our lab, and I can see it automatically rebooted several times.
> Below is a part of my log with timestamp:
> .....
> [2024-10-22 17:28:26.921] [  OK  ] Started OF-DPA OFAgent.
> [2024-10-22 17:28:26.978] [  OK  ] Started OF-DPA gRPC API.
> [2024-10-22 17:28:27.037] [  OK  ] Started onlpd platform manager daemon.
> [2024-10-22 17:28:28.628] 
> [2024-10-22 17:28:28.629] BISDN Linux 5.2.1 accton-as4610-30 ttyS0
> [2024-10-22 17:28:28.629] 
> [2024-10-22 17:28:28.629] accton-as4610-30 login: 
> [2024-10-22 17:30:17.165] 
> [2024-10-22 17:30:17.165] U-Boot 2012.10-ge5a5544 (Apr 18 2017 - 11:47:41) - 2012.10.0.5
> [2024-10-22 17:30:17.165] 
> [2024-10-22 17:30:17.165] DCO:   32 (PASS)
> [2024-10-22 17:30:17.165] Device:Helix4 (0xdc14)
> .....
> I am working on this issue, and will keep you updated.
> 
> .....
> From the results, this auto-rebooting should be due to the NOS, since you can see in ONIE the switch stays alive (which is also my test result).
> 
> I asked if you power the switch with both PSU because I tested with these cases,
> (1) First power up with 1 PSU: the switch auto-reboots several times in 1 hour.
> (2) Then I powered up the 2nd PSU: the switch stays up for 17 hours:
> 
> accton-as4610-30:~$ cat /etc/os-release 
> ID=bisdn-linux
> NAME="BISDN Linux"
> VERSION="5.2.1 (Ortolana)"
> VERSION_ID=5.2.1
> PRETTY_NAME="BISDN Linux 5.2.1 (Ortolana)"
> DISTRO_CODENAME="Ortolana"
> BUILD_ID="20241016080735"
> accton-as4610-30:~$ uptime
>  03:12:56 up 17:06,  1 user,  load average: 3.25, 3.21, 3.26
> I will attach my test log for your reference. I powered the 2nd PSU with this note in the line:
> [2024-10-22 18:31:04.988] accton-as4610-30:~$ ##############plug both PSU power cord
>  
> Please test to power with both PSU, and check if you also see the same result?
> Overall, since this is an issue due to the NOS, I suggest you could consult with the OS vendor BISDN.

### Reply from BISDN
We do not have any AS4610-30P devices in our lab, but the PSUs of our AS4610-54P devices caused reboots when accessing certain values and needed to be replaced by Edgecore. My guess is that the same issue affects your AS4610-30P. Please check with Edgecore whether your PSUs need replacement as well.

### Resolution:
Edgecore tested your 5.2.1 version on a AS4610-30P in their labs and concluded that it is indeed the NOS causing the issue and not the PSUs. They recommended contacting yourselves to look into this further. Attached is a log to support these findings provided by EdgeCore. There is clearly some kind of issue with the NOS which is causing the PSUs to glitch out, not only on the AS4610-30P but also the AS4610-54P. Could someone look into this further please and find a solution to the problem. Many thanks

[1022_4610-30P_bisdn_reboot-2.zip](https://github.com/user-attachments/files/17525244/1022_4610-30P_bisdn_reboot-2.zip)

**Comment by KanjiMonster** [comment]
Please boot into ONIE rescue (break into U-Boot shell and issue `run onie_rescue`), and try to run the following shell script:

```
#!/bin/sh

# 0x58 for PSU1, 0x59 for PSU2
PSU=0x58

mknod /dev/i2c-16 c 89 16

while true; do
    # psu_v_out
    i2cget -y 16 $PSU 0x8b w >/dev/null
    # psu_i_out
    i2cget -y 16 $PSU 0x8c w >/dev/null
    # psu_p_out
    i2cget -y 16 $PSU 0x96 w >/dev/null
    echo -n .
done
```

If it resets after a short while, your PSUs are older revisions that are affected by a known defect, triggered by https://github.com/opencomputeproject/OpenNetworkLinux/commit/24efd4f46987a552a622434a881ae68d8a2d353.

**Comment by abbahmed** [comment]
Dear BISDN Team,

I am reaching out regarding a critical issue with the AS4610-30P switch that appears to be triggered by a firmware bug in certain PSU models. Specifically, the issue is linked to the [YM-1601A, A01R] PSU, which causes the switch to reboot when subjected to rapid I2C polling.

#Details of the Issue

	1.	The issue arises when the I2C polling function is triggered in ONIE or when using BISDN NOS.
	2.	Reproducing the issue:
	•	I executed the following script in ONIE rescue mode to simulate polling:

#!/bin/sh  
PSU=0x58  
mknod /dev/i2c-16 c 89 16  
while true; do  
    i2cget -y 16 $PSU 0x8b w >/dev/null  
    i2cget -y 16 $PSU 0x8c w >/dev/null  
    i2cget -y 16 $PSU 0x96 w >/dev/null  
    echo -n .  
done  


	•	The switch reboots after approximately 30 seconds when this script is executed (only PSU1 powered).

	3.	Upon internal review with Edgecore, they confirmed that the reboot is caused by a known PSU firmware bug in the [YM-1601A, A01R] model. This bug is triggered by rapid polling over I2C.
	4.	The root cause appears to be related to the implementation of the I2C polling function in commit 24efd4f on the Open Network Linux (ONL) project.

#Request

To mitigate this issue for affected PSU models, I kindly request that BISDN consider implementing a software workaround by either:
	1.	Disabling or modifying the I2C polling function to avoid triggering the PSU bug.
	2.	Providing a configuration option to bypass this polling functionality for users with affected hardware.

This issue currently impacts the stability of the AS4610-30P when running your NOS with a single PSU, and it would greatly improve reliability if addressed.

**Comment by KanjiMonster** [comment]
Does http://repo.bisdn.de.s3-eu-central-1.amazonaws.com/latest/generic-armel-iproc/main/onie-bisdn-full-generic-armel-iproc-202411280815.bin work for you?

**Comment by abbahmed** [comment]
Okay, no problem, I will make a copy of this file
