### ISSUE TITLE
AS4610: Install fails with previous ONL install

### ISSUE THREAD

**Issue by Keno** [bisdn/bisdn-linux#72]
I'm seeing the following on as AS4610 switch that had a prior ONL install:
```
ONIE: Executing installer: http://repo.bisdn.de/pub/onie/accton-as4610/onie-bisdn-accton-as4610-v4.8.1.bin
Image build date: 2022-10-05
Verifying image checksum ... OK.
Preparing image archive ... OK.
DEBUG: onl_platform=arm-accton-as4610-54-r0
DEBUG: onl_baseplatform=arm-accton-as4610-54
BISDN Linux Installer
DEBUG: onie_partition_type=gpt
DEBUG: firmware=u-boot
removing partition 1 (Linux)
removing partition 2 (Linux)
removing partition 3 (Linux)
removing partition 4 (Linux)
Creating new BISDN Linux gpt partition /dev/sda5 ...
Could not create partition 5 from 34 to 12582945
Unable to set partition 5's name to 'BISDN-Linux'!
Error encountered; not saving changes.
Error: Unable to create partition 5 on /dev/sda
Failure: Unable to install image: http://repo.bisdn.de/pub/onie/accton-as4610/onie-bisdn-accton-as4610-v4.8.1.bin
```

The partition layout is:
```
Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048          262143   127.0 MiB   8300  Linux filesystem
   2          262144          524287   128.0 MiB   8300  Linux filesystem
   3          524288         2621439   1024.0 MiB  8300  Linux filesystem
   4         2621440        15720447   6.2 GiB     8300  Linux filesystem
```

**Comment by Keno** [comment]
I was able to eventually work around this by installing the Accton DIAG image instead, which had the following partition layout:
```
Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048          526335   256.0 MiB   8300  ACCTON-DIAG
```
for which the installation succeeded.

**Comment by jklare** [comment]
Hi @Keno,
in genereal it should not matter which NOS was installed on the switch prior to installing BISDN Linux, but i have seen issues similar to the one you describe above before when not running an uninstall before installing a new NOS. Did you run uninstall before or just a direct install after booting straight from the NOS into ONIE ?
Cheers,
Jan

**Comment by KanjiMonster** [comment]
> ```
> removing partition 1 (Linux)
> removing partition 2 (Linux)
> removing partition 3 (Linux)
> removing partition 4 (Linux)
> Creating new BISDN Linux gpt partition /dev/sda5 ...
> ```

If it removed 4 partitions, then the next partition should be sda1, not sda5, so it seems to have failed removing the partitions.

> 
> The partition layout is:
> 
> ```
> Number  Start (sector)    End (sector)  Size       Code  Name
>    1            2048          262143   127.0 MiB   8300  Linux filesystem
>    2          262144          524287   128.0 MiB   8300  Linux filesystem
>    3          524288         2621439   1024.0 MiB  8300  Linux filesystem
>    4         2621440        15720447   6.2 GiB     8300  Linux filesystem
> ```

as evident by the partitions shown here.

Do you have a link to the exact ONL image you had installed previously? I faintly remember someone else having issues directly installing BISDN Linux because the previous NOS ignored the `DEBUG: onie_partition_type=gpt` part and created MS DOS partitions.

**Comment by Keno** [comment]
> Did you run uninstall before or just a direct install after booting straight from the NOS into ONIE ?

I did run `uninstall`, yes.

**Comment by KanjiMonster** [comment]
> > Do you have a link to the exact ONL image you had installed previously?
> 
> I'm pretty sure it would have been: https://opennetlinux.org/binaries/latest-DEB9-ARMEL-SWI.installer

Great, thanks. I found that one as well, but seeing as it was from 2019, wondered if there's a newer one in a non obvious location.

> I did run `uninstall`, yes.

So having the ONL image installed even broke `uninstall`? Then my immediate idea for fixing that likely wouldn't even have helped (i.e. invoke an uninstall from our installer).

**Comment by KanjiMonster** [comment]
After reviewing the [ONL installer code](https://github.com/opencomputeproject/OpenNetworkLinux/blob/master/packages/base/all/vendor-config-onl/src/python/onl/install/BaseInstall.py#L1103), it reformats the disk as msdos/MBR, deleting the ACCTON-DIAG partition in the process, then uses up all space.

So there really isn't much we can do apart from reformating as gpt again (the ONL installer didn't leave enough space for converting it to gpt). But since the DIAG partition is gone anyway, there is also nothing of value left, so that's fine.

**Comment by AlD** [comment]
I ran into what looks like the exact same issue with 4.8.3:

```
ONIE:/ # onie-nos-install http://192.168.0.2/onie-bisdn-accton-as4610-v4.8.3.bin
discover: Rescue mode detected. No discover stopped.
Info: Fetching http://192.168.0.2/onie-bisdn-accton-as4610-v4.8.3.bin ...
Connecting to 192.168.0.2 (192.168.0.2:80)
installer            100% |*******************************|   122M  0:00:00 ETA
ONIE: Executing installer: http://192.168.0.2/onie-bisdn-accton-as4610-v4.8.3.bin
Image build date: 2023-02-14
Verifying image checksum ... OK.
Preparing image archive ... OK.
DEBUG: onl_platform=arm-accton-as4610-54-r0
DEBUG: onl_baseplatform=arm-accton-as4610-54
BISDN Linux Installer
DEBUG: onie_partition_type=gpt
DEBUG: firmware=u-boot
removing partition 2 (PICOS)
removing partition 3 (PICOS)
removing partition 4 (PICOS)
Creating new BISDN Linux gpt partition /dev/sda5 ...
Could not create partition 5 from 34 to 12582945
Unable to set partition 5's name to 'BISDN-Linux'!
Error encountered; not saving changes.
Error: Unable to create partition 5 on /dev/sda
Failure: Unable to install image: http://192.168.0.2/onie-bisdn-accton-as4610-v4.8.3.bin
```
```
ONIE:/ # fdisk -l

Disk /dev/mtdblock0: 0 MB, 917504 bytes
255 heads, 63 sectors/track, 0 cylinders
Units = cylinders of 16065 * 512 = 8225280 bytes

Disk /dev/mtdblock0 doesn't contain a valid partition table

Disk /dev/mtdblock1: 0 MB, 65536 bytes
255 heads, 63 sectors/track, 0 cylinders
Units = cylinders of 16065 * 512 = 8225280 bytes

Disk /dev/mtdblock1 doesn't contain a valid partition table

Disk /dev/mtdblock2: 0 MB, 65536 bytes
255 heads, 63 sectors/track, 0 cylinders
Units = cylinders of 16065 * 512 = 8225280 bytes

Disk /dev/mtdblock2 doesn't contain a valid partition table

Disk /dev/mtdblock3: 7 MB, 7340032 bytes
255 heads, 63 sectors/track, 0 cylinders
Units = cylinders of 16065 * 512 = 8225280 bytes

Disk /dev/mtdblock3 doesn't contain a valid partition table

Disk /dev/sda: 31.6 GB, 31641829376 bytes
256 heads, 63 sectors/track, 3831 cylinders
Units = cylinders of 16128 * 512 = 8257536 bytes

   Device Boot      Start         End      Blocks  Id System
/dev/sda1               1        3832    30900223+ ee EFI GPT
```
