### ISSUE TITLE
Switch was recognized as AS4610-30 instead of AS4610-54 in bisdn linux 5.1

### ISSUE THREAD

**Issue by gmuehl4241** [bisdn/bisdn-linux#99]
Hi,

with bisdn linux 5.1 my switch was recognized as AS4610-30 instead of AS4610-54.  This caused the interface not to come up. I changed /etc/onl/platform from "arm-accton-as4610-30-r0" to "arm-accton-as4610-54-r0" manually.  That resolved the issue.

onlpdump -o
        Product Name: 4610-54T-O-AC-B
        Part Number: F0PEC4654004Z
        MAC Range: 55
        Manufacturer: Accton
        Manufacture Date: 03/17/2019 04:52:33
        Vendor: Edgecore
        Platform Name: arm-accton_as4610_30-r0
        Label Revision: R01A
        Country Code: CN
        Diag Version: 001.9
        ONIE Version: 2016.05.00.04

Best regards,

GM

**Comment by KanjiMonster** [comment]
Thank you for opening a ticket. Obviously you shouldn't need to update it.

> Platform Name: arm-accton_as4610_30-r0

looks like this AS4610 has a wrongly programmed ONIE platform in its EEPROM, which I suspect is the source of misdetection.

**Comment by KanjiMonster** [comment]
Did you ever update ONIE?

**Comment by KanjiMonster** [comment]
Since we had the exact same symptoms after installing an AS4610-30 ONIE on a AS4610-54 switch, I think this is what was happened here. (Re-)Installation of the appropriate ONIE should fix the issue.

If this wasn't the issue, and it does not fix it, feel free to reopen it.
